### ISSUE TITLE
More configurable build

### ISSUE THREAD

**Issue by texastoland** [nwolverson/vscode-ide-purescript#13]
1. <s>Not configurable per project. Perhaps check for a npm `build:purs` script.</s>
2. Cannot be triggered by the standard build command. Perhaps generate a task like for npm. It'd be nice to offer psa filtering in the template.
3. <s>No problem matchers for builds triggered by npm, WebPack, etc.</s> #17
4. <s>Too many notifications.</s> #15
5. <s>Build failure not reported. Perhaps also open problems view when problems exist.</s> #14
6. Automatic rebuild has never worked for me. (Open a separate issue when I figure out why.)
7. <s>No test command.</s> #16

These might also apply to the [Build package](https://atom.io/packages/build) when I used Atom.

**Comment by nwolverson** [comment]
1. VS code has per project configuration - .vscode directory? Use 'configure workspace settings'. So I think this is already possible. The configuration you choose might be to run `npm purs:build` (I've never seen a project where that particular npm task was the build command; if anything I'd default to `build` as I think pscid uses this).

I think there's a place for a shared 'project settings' file between multiple PureScript tools, with e.g. build commands, source globs, error codes to ignore, but this might also tie into some other discussions.

2/3 - I think this is the same? The thing is the errors etc all work by using psc JSON output, while VS code problem matchers seem half-assed only supporting regexes. I remember the nightmare of trying to keep valid regex matchers for psc compiler errors before the JSON output was introduced, and it was very fragile - the compiler doesn't give single line errors. I see that Code is no longer restricted to single line regexes though, so it might be possible - but from what I read I'm not convinced.

Needs a proper API.

The problem is there you also lose the nice functionality like providing quick-fix suggestions.

(Atom Build is worse in a sense, that you can't even cause your matcher to rank higher than the built-in ones, when I looked it was assumed that the build tool was 1:1 with the problem matcher. Something was possible but it wasn't nice)

4. Not sure what this would do - a separate command or something executed on successful build?

5 - This is the best bit...

**Comment by texastoland** [comment]
> Use 'configure workspace settings'.

Wow I didn't know. Much better solution.

> (I've never seen a project where that particular npm task was the build command; if anything I'd default to build as I think pscid uses this).

I was trying to think of a good convention. `build` is typically an aggregate command.

> this might also tie into some other discussions.

bodil/pulp#192

> I think this is the same?

2) is different. VS Code encourages generating tasks from templates for commands that tie into build and test shortcuts.

> I see that Code is no longer restricted to single line regexes though, so it might be possible

Yeah I've used it and works well. I'm suggesting as an added convenience not forgoing JSON by default. In practice I usually build from a script.

> Needs a proper API.

For reporting build failure?

**Comment by nwolverson** [comment]
As well as that pulp discussion - the general discussion around PS specific package manager & config

By proper API - I mean for problem matching, rather than some conglomeration of regexes we could do this nicely if it had an API (obviously with a regex implementation that does the current thing).

On the multi line regex - I think the fact the actual error spans multiple lines, with multiple blank lines etc, will make this hard if not impossible. But I may misunderstand the docs - happy for someone to prove me wrong.

Opened #14 #15 #16 to track specific things

Re 2),  I don't see that task templates are available to language extensions - seems to be hard wired for built in things. ICBW

**Comment by texastoland** [comment]
Okay so the remaining two are dependent on API. I'll investigate late in the week. Thanks!

**Comment by nwolverson** [comment]
I added one for the problem matcher - as certainly something can be done, somehow, just a question of how good and how much effort.  The task template, yes it depends if there's a suitable extension point.

On your rebuild - if you have tooltips/completion working and current compiler it's usually quite reliable - unless some oddity of running multiple concurrent build tools.

**Comment by texastoland** [comment]
I have no idea what's wrong there. I've worked on multiple packages and experienced it. I just haven't read the logs yet.

**Comment by texastoland** [comment]
Closing this and I'll open one for tasks if I find an API 🙏
