### ISSUE TITLE
Rework README

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/vscode-ide-purescript#156]
Could do with a clearer display of features, something in depth after the bullet point "what is the objective of the extension" section

Maybe check https://github.com/nwolverson/atom-ide-purescript/ and elsewhere for inspiration

**Comment by cheery** [comment]
I did two minor modifications to existing text it had, otherwise I kept it like it was since it's ok.

Aside trying to explain the tool itself, I tried to add some detail of things that a person might like to look up in order to setup this thing. The README becomes slightly larger than it otherwise would be, but I believe it is also more helpful this way. These are things I actually did end up looking for, so they ought to be all useful here.

Next I think this will need few pics. I think I'll do something, but nothing too complex such that it'd confuse, and grab shots of these features in real use.

After we got some pics, we'll look at this together and see what else?

**Comment by cheery** [comment]
I'm sorry it took me some time, otherwise well-spent. Here's the gifs.

![addClause](https://user-images.githubusercontent.com/1215420/99907495-b58d4780-2ce5-11eb-8fa4-4d3f6f402560.gif)

![caseSplit](https://user-images.githubusercontent.com/1215420/99907505-c211a000-2ce5-11eb-98f3-f7955b36f889.gif)

![gotoDef](https://user-images.githubusercontent.com/1215420/99907507-c76eea80-2ce5-11eb-8528-44c965e4abb6.gif)

![gotoSymbol](https://user-images.githubusercontent.com/1215420/99907511-cb027180-2ce5-11eb-9fa1-4ee5db77ff44.gif)

![tooltipType](https://user-images.githubusercontent.com/1215420/99907514-cf2e8f00-2ce5-11eb-87e0-764b4d333c06.gif)

I'll check how the readme has changed during this, merge the updates and then put these in. Also going to re-check the texts again so that they are fine.
