### ISSUE TITLE
File watcher error with spago install

### ISSUE THREAD

**Issue by wclr** [nwolverson/vscode-ide-purescript#169]
There the [error may occur ](https://github.com/purescript/spago/issues/726) when performing `spago install` in terminal on windows. To get rid need to add settings:

```json
"files.watcherExclude": {    
    "**/.spago/**": true
  },
```

I'm not sure, but it probably not possible to affect user settings via the extension? So then it should be included in docs.

**Comment by nwolverson** [comment]
Correct, I don't think the extension is relevant here, though maybe worth checking the LS-watch settings, I think that's fine.

Presumably that's an issue with all watchers, though I guess you're maybe not likely to be watching the root directory rather than src or output depending what they're doing.

Should we also suggest excluding `output` and any others?

**Comment by wclr** [comment]
> Should we also suggest excluding output and any others?

`.spago` is a special folder and can be (preferably) added to global user settings. As for `output` folder it is a project's scope, so user should decide if it need to be excluded. Watching it probably should not cause the errors, but from editor's performance perspective it might be excluded, but it can affect some behaviour if the code from output is integrated with some other external js code that requires it, so this is the userland I think.

**Comment by nwolverson** [comment]
Added a note to the README.
