### ISSUE TITLE
Indentation settings not respected?

### ISSUE THREAD

**Issue by Chiel92** [nwolverson/vscode-ide-purescript#179]
Hi, thanks for the great plugin.

After pressing enter to open a new line, the indentation width is 4 spaces instead of 2 spaces. This only happens in .purs files. The indentation size is set correctly using a .editorconfig file, and pressing tab explicitly indeed inserts two spaces.

![image](https://user-images.githubusercontent.com/1030961/118719220-7c630980-b828-11eb-9e44-492495c61969.png)

**Comment by nwolverson** [comment]
Firstly, this extension is not responsible for purescript syntax, that would be vscode-language-purescript.

Secondly, I think you're not quite describing the behaviour fully, at least in my experience in some (even most) places hitting enter will align with the current indentation, there seems to be a case as you highlight above where the indentation is increased.

I can only assume this derives from the default VSCode indentation rules - there was an attempt to define PureScript indentation rules here which was reverted due to being unhelpful: https://github.com/nwolverson/vscode-language-purescript/pull/12

I've raised an issue in the other repo.
