### ISSUE TITLE
Question:Can it support data constructor autocomplete?

### ISSUE THREAD

**Issue by WendaoLee** [nwolverson/vscode-ide-purescript#219]
For instance:
```purescript
data Test = Test{
    id::String,
    num::Number
}

d::Test
d = Test{
    id:"test",
    num:1.3
}
```
When I write `d = Test{}`,it would be great joy of showing recording's info:

![](https://raw.githubusercontent.com/WendaoLee/WendaoLee/main/pic/purescript-ide-autocomplete.png)

But sadly,it gets nothing when I press enter.And no tooltip when I try to complete the record.😭

Is there anyway to support this feature?Or this feature exsit but not show because of my inappropriate setting?If so,could some guys tell me how to change that?

**Comment by nwolverson** [comment]
The data constructor `Test` should be autocomplete with vscode default settings, which is to say after typing `Te`, if you hit your accept completion keybind, should complete to `Test`. There's a setting "Accept Suggestion on Enter", otherwise it will be on hitting tab.

There is no completion for records, it's a difficult feature to support (because the record part of the type `{id::String,num::Number}` is a standalone type and there are unlimited options for that).

**Comment by WendaoLee** [comment]
> 

Yep,I forgot unlimited types.😽All in all,thank you for your reply and works.
