### ISSUE TITLE
Add "packagePath" setting

### ISSUE THREAD

**Issue by andyarvanitis** [nwolverson/vscode-ide-purescript#31]
For people starting to use psc-package (or whatever else) instead of bower, it would be nice to have the option to override the "bower_components" search path. I can create and submit a PR for this if you like.

**Comment by nwolverson** [comment]
I feel like this should use `psc-package sources` rather than working it out itself? I don't think a simple glob can work as there can be multiple versions in the directory. (Also I forget but think this is just for source navigation?)

I had a thought that this could be triggered by existence of `psc-package` but a menu option to enable is good

**Comment by andyarvanitis** [comment]
Ah, you're right, that wouldn't work properly.  Yeah, it's for symbol navigation/search, which I noticed  wasn't working for me when using just psc-package (unless I worked around it with a symbolic link from `.psc-package` to `bower_components`, or equivalent). I can close this issue and open another as just "Support psc-package", unless you've already got it tracked/planned.

**Comment by nwolverson** [comment]
Regardless what the ideal solution is I'd certainly accept a patch which makes the source files glob configurable, even if you need to pay attention to your package sets rather than having it auto-work out of the box

**Comment by andyarvanitis** [comment]
Sounds good

**Comment by nwolverson** [comment]
Resolved via 9b5ea53b2bf9c48a0f7ca187c84e710fa0d4d0c7
