### ISSUE TITLE
Display the module's name in suggestions

### ISSUE THREAD

**Issue by jgoux** [nwolverson/vscode-ide-purescript#44]
Hello,

I often auto-import a function from a suggestion from the wrong module because I'm not able to see the module's name in it.

Example : 
![image](https://cloud.githubusercontent.com/assets/1443499/24033579/ea8c3efa-0aed-11e7-9327-ef4354d41412.png)

Would it be possible to add the module's name in the suggestions ?

**Comment by nwolverson** [comment]
I think this is restricted by the set of fields vscode permits (unless we mangle the name itself) - if you have an example from a different language plugin or the vscode docs, as to where this would go, that would be useful here.

Related issue - there is discussion on providing some metadata from psc-ide to group re-exported modules, which would allow suppressing most of these cases avoiding the issue in the most part.

**Comment by otbe** [comment]
Same problem here. Im very new to PureScript and importing the wrong function (nubBy from List.Lazy instead of List) lead to type errors which are not easy to understand for beginners :)

This is the way VSCode handles this for TypeScript:
<img width="219" alt="bildschirmfoto 2017-03-19 um 16 26 10" src="https://cloud.githubusercontent.com/assets/3391052/24082153/0713c0f0-0cc1-11e7-9008-37410eb5d3d2.png">

And off topic: docs + signature + extended view
<img width="536" alt="bildschirmfoto 2017-03-19 um 16 26 22" src="https://cloud.githubusercontent.com/assets/3391052/24082155/07380ee2-0cc1-11e7-8787-0fef1693aeca.png">
When clicking on i-icon:
<img width="439" alt="bildschirmfoto 2017-03-19 um 16 26 31" src="https://cloud.githubusercontent.com/assets/3391052/24082154/073743f4-0cc1-11e7-8c9f-de0f4e36e5c3.png">

Thank you!

**Comment by nwolverson** [comment]
Unfortunately none of those examples are immediately useful, what we would want is the completion listing (2nd image in previous comment) to show the module name, as it already shows the type there's no use in collapsing them with a "pick which option" 2nd step unless the info can be combined.

I'll definitely look at squeezing it in somehow.

Regarding documentation, that will happen in the future when it's available from psc-ide, see https://github.com/purescript/purescript/issues/2349

**Comment by nwolverson** [comment]
Some options. Bear in mind this is a bad example, as the re-export specific change would disambiguate these, but imagine I picked genuinely differentt defined with the same name in different modules.

![screen shot 2017-03-20 at 21 48 53](https://cloud.githubusercontent.com/assets/2770891/24123539/ccd03804-0db7-11e7-9062-d8024862dc51.png)
![screen shot 2017-03-20 at 21 52 07](https://cloud.githubusercontent.com/assets/2770891/24123542/cced985e-0db7-11e7-84fa-45811340f30e.png)
![screen shot 2017-03-20 at 21 53 35](https://cloud.githubusercontent.com/assets/2770891/24123541/ccecb6b4-0db7-11e7-99f8-b5640613391e.png)

First seems unreadable due to lack of alignment of the identifier itself, not sure which I prefer of other 2 options.

**Comment by otbe** [comment]
I like the third one because the type definition is complete visible.
I wonder how it would look if you add docs to the third one?

**Comment by jgoux** [comment]
The third one too! 👍

**Comment by nwolverson** [comment]
This should now be in (the third one)

**Comment by jgoux** [comment]
This is awesome, thanks a lot!
