### ISSUE TITLE
Purescript: Build command 

### ISSUE THREAD

**Issue by vstastny** [nwolverson/vscode-ide-purescript#6]
On Windows, this command does nothing (probably connected with the other issue). Is it necessary to provide some special setting when using on Windows? Could you please give a hint how to?
By the way, should it work the same way as in Atom, i.e. build once saved?
Thank you.

**Comment by nwolverson** [comment]
If you edit your user or workspace config, take the default commend and add `.cmd` (so `pulp.cmd ...`).

That's assuming it's in your `PATH`, otherwise you should add it or specify a full path (without spaces at this time...)

I think there is no build on save at the moment, there is a build command you can invoke from the command palette (or set yourself a keybinding).

**Comment by vstastny** [comment]
I added this row into Workspace settings:
"pulp.cmd": "..."
I guess I did it incorrectly since it has no effect. I am sorry, i am new to vs code. Could you please advice? Also I do not know where should the pulp.cmd be located. On my machine, pulp files are located in ..\AppData\Roaming\npm\node_modules\pulp\. All of them are .js or .purs.

**Comment by nwolverson** [comment]
So obviously it should look like the existing setting (you are taken to the list of defaults when you edit your settings). So the value to use would be:
```
{
    "purescript.buildCommand": "pulp.cmd build --no-psa --json-errors",
}
```

If npm global install location is set into your path you're good, otherwise I guess you can check `where pulp` in a  command line (bear in mind you need to use the `.cmd` version).

**Comment by vstastny** [comment]
Works. Thank you again.
