### ISSUE TITLE
Autoimport imports things already in scope via re-export

### ISSUE THREAD

**Issue by natefaubion** [nwolverson/vscode-ide-purescript#78]
If I have `import Prelude` and autcomplete on `<<<` it adds an import for `Data.Function ((<<<))`, which is unnecessary.

**Comment by nwolverson** [comment]
This is to do with re-exports, as in fact you are importing `Data.Function.(<<<)` not `Prelude.(<<<)`.

There are some changes around re-export handling but I think the details are waiting on 0.11.6 in order to work. Then we should see just one autocompletion option rather than redundant versions, and by default in this case it will be the `Prelude` version, leading to no extra import.

**Comment by nwolverson** [comment]
This seems to be good with 0.11.6 for me with the settings `purescript.autocompleteGrouped`, `purescript.importsPreferredModules: ["Prelude"]` (as per defaults).
